services:
  safe-host:
    build:
      context: ./Safe.Host
      dockerfile: Dockerfile
    image: ${SAFE_HOST_IMAGE:-safe-host:latest}
    env_file:
      - ../auth-host.env
    container_name: safe-host
    restart: unless-stopped
    environment:
      Auth__Introspection__ClientSecret: ${OIDC_SVC_INTROSPECTOR_SECRET}
    expose:
      - "5001"
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
    driver: bridge
